<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_field</name>
   <tag></tag>
   <elementGuidId>b4567bf7-e9df-4a1e-947f-80507892032c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/tl_search&quot;]/android.widget.FrameLayout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/tl_search&quot;]/android.widget.FrameLayout</value>
      <webElementGuid>485f0eca-aab2-44a7-aaf3-7e97c648d3b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
