<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>back_button</name>
   <tag></tag>
   <elementGuidId>51fab33f-db60-4496-b155-6c7dd95aa052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.widget.ImageView[@resource-id=&quot;id.binar.fp.secondhand:id/btn_back&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.ImageView[@resource-id=&quot;id.binar.fp.secondhand:id/btn_back&quot;])[1]</value>
      <webElementGuid>9c6f1d2a-664c-4e47-8829-497e55d31611</webElementGuid>
   </webElementProperties>
</WebElementEntity>
