<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconPhotoProduct</name>
   <tag></tag>
   <elementGuidId>eca82511-5f4e-4e3d-9758-eb658f1d73db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.ImageView[@resource-id=&quot;id.binar.fp.secondhand:id/iv_product_image&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.ImageView[@resource-id=&quot;id.binar.fp.secondhand:id/iv_product_image&quot;]</value>
      <webElementGuid>c4978165-ae8d-41e3-bc9f-891625f2a01c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
