<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lokasi_field</name>
   <tag></tag>
   <elementGuidId>e449b013-9933-4508-a060-ff377a74c43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_location&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_location&quot;]</value>
      <webElementGuid>a90e31eb-1be1-43f9-b66b-30fecae33592</webElementGuid>
   </webElementProperties>
</WebElementEntity>
