<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaProduk_field</name>
   <tag></tag>
   <elementGuidId>2bd101b8-4978-43f1-b515-2033110c49d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@resource-id=&quot;id.binar.fp.secondhand:id/et_product_name&quot;]</value>
      <webElementGuid>545c7a73-b680-4439-bc14-2cfa143b903e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
