<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kota_field</name>
   <tag></tag>
   <elementGuidId>4e0b4982-53fa-46ed-ad80-981e3f08d607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.widget.ImageView[@resource-id=&quot;id.binar.fp.secondhand:id/shapeableImageView&quot;])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.ImageView[@resource-id=&quot;id.binar.fp.secondhand:id/shapeableImageView&quot;])[3]</value>
      <webElementGuid>e59c9dbe-ee37-446a-bf47-c4fa3040dbd2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
