<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xButton_field</name>
   <tag></tag>
   <elementGuidId>cba47a31-eccf-4e46-90d5-284a3d73fcbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/text_layout&quot;]/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.LinearLayout[@resource-id=&quot;id.binar.fp.secondhand:id/text_layout&quot;]/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout</value>
      <webElementGuid>e0debfea-7057-4d9a-987f-9821d3c5f5d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
